### ISSUE TITLE
Create dockerized code to create annotation-files on zarr grid from work files

### ISSUE THREAD

**Issue by nilsolav** [CRIMAC-WP4-Machine-learning/CRIMAC-annotationtools#6]
We would like to move the label generation code to this repository. We then separate the preprocessing of sv files and the generation of labels.

We need to generate a docker image with versioning (similar logic to [CRIMAC-preprocessing-korona](https://github.com/CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing-korona)).

The conatainer must take the zarr files and the work files as input and generate the zarr based annotations, and the code should be based on the annotation generated  from the [CRIMAC-preprocessing](https://github.com/CRIMAC-WP4-Machine-learning/CRIMAC-preprocessing).

**Comment by tomaszfurmanek** [comment]
docker image with versioning is ready
